{% set name = "cliche" %}
{% set version = "0.7.53" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cliche-{{ version }}.tar.gz
  sha256: 61cda4a2779a2f8ed6157ef4d0b07e2d1651a9a887b639e53acc7517a6d78c6c


build:
  number: 0
  noarch: python
  entry_points:
    - cliche = cliche.__init__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - cliche
  commands:
    - pip check
    - cliche --help
  requires:
    - pip

about:
  home: https://github.com/kootenpv/cliche
  summary: A minimalistic CLI wrapper out to be the best
  license: MIT
  license_file: license.txt

extra:
  recipe-maintainers:
    - kootenpv
