{% set name = "cliche" %}
{% set version = "0.7.43" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cliche-{{ version }}.tar.gz
  sha256: 0e49c333a8cb1e8f3fdd969dc31951f17265c21b26bc640c342c06ad2033f773


build:
  number: 0
  noarch: python
  entry_points:
    - cliche = cliche.__init__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - cliche
  commands:
    - pip check
    - cliche --help
  requires:
    - pip

about:
  home: https://github.com/kootenpv/cliche
  summary: A minimalistic CLI wrapper out to be the best
  license: MIT
  license_file: license.txt

extra:
  recipe-maintainers:
    - kootenpv
