{% set name = "cliche" %}
{% set version = "0.7.63" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cliche-{{ version }}.tar.gz
  sha256: c132aa05ad4167ae83cf95f437a2a7423649f9958e9f88e587974b19d08b70d0


build:
  number: 0
  noarch: python
  entry_points:
    - cliche = cliche.__init__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - cliche
  commands:
    - pip check
    - cliche --help
  requires:
    - pip

about:
  home: https://github.com/kootenpv/cliche
  summary: A minimalistic CLI wrapper out to be the best
  license: MIT
  license_file: license.txt

extra:
  recipe-maintainers:
    - kootenpv
