{% set name = "cliche" %}
{% set version = "0.7.44" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cliche-{{ version }}.tar.gz
  sha256: eefd03f6a4d84d4a4a6fa8401af45583b199de89c2ebb712daefb7ba1667fde0


build:
  number: 0
  noarch: python
  entry_points:
    - cliche = cliche.__init__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - cliche
  commands:
    - pip check
    - cliche --help
  requires:
    - pip

about:
  home: https://github.com/kootenpv/cliche
  summary: A minimalistic CLI wrapper out to be the best
  license: MIT
  license_file: license.txt

extra:
  recipe-maintainers:
    - kootenpv
